/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('@iconify/vue')['Icon']
    InputCardnumber: typeof import('./src/components/InputCardnumber.vue')['default']
    InputCVC: typeof import('./src/components/InputCVC.vue')['default']
    InputExpire: typeof import('./src/components/InputExpire.vue')['default']
    InputName: typeof import('./src/components/InputName.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    TheForm: typeof import('./src/components/TheForm.vue')['default']
    TheFormLabel: typeof import('./src/components/TheFormLabel.vue')['default']
  }
}
